name: namsefni
channels:
  - conda-forge
  - defaults
dependencies:
  - pypandoc=1.*
  - sphinx=8.*
  - python=3.12.*
  #  - sphinx-rtd-theme=2.0.*
  - sphinxcontrib-youtube
  - sphinxcontrib-bibtex
  - pyyaml=6.*
  - jinja2=3.*
  - sphinx-autobuild=2024.4.16
  - sphinx-togglebutton=0.3.*
  - pip=24.*
  - pip:
    - typer[all]
    - rich
    - -e ./cli
    - sphinxcontrib-katex==0.9.10
    - sphinx-copybutton==0.5.2
    - sphinx_rtd_theme @ git+https://github.com/readthedocs/sphinx_rtd_theme.git@humitos/plan-3.0
    - sphinxcontrib-custombutton @ https://github.com/edbook/sphinxcontrib-custombutton/archive/refs/tags/v2.0.zip
    - sphinxcontrib-datacamp @ https://github.com/edbook/sphinxcontrib-datacamp/archive/refs/tags/v2.0.zip
    - sphinxcontrib-geogebra @ https://github.com/edbook/sphinxcontrib-geogebra/archive/refs/tags/v2.0.zip
    - sphinxcontrib-hoverrole @ https://github.com/edbook/sphinxcontrib-hoverrole/archive/refs/tags/v2.0.15.zip
    - sphinxcontrib-panopto @ https://github.com/edbook/sphinxcontrib-panopto/archive/refs/tags/v2.0.1.zip
    - sphinxcontrib-questionnaire @ https://github.com/edbook/sphinxcontrib-questionnaire/archive/refs/tags/v2.0.9.zip
    - sphinxcontrib-sagecell @ https://github.com/edbook/sphinxcontrib-sagecell/archive/refs/tags/v2.0.zip
    - sphinxcontrib-scrolldepth @ https://github.com/edbook/sphinxcontrib-scrolldepth/archive/refs/tags/v2.0.zip
    - sphinxcontrib-toggleblock @ https://github.com/edbook/sphinxcontrib-toggleblock/archive/refs/tags/v2.0.zip
